<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Adham.Cli</RootNamespace>
    <AssemblyName>adham</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Adham.Cli.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DiffPlex" />
    <ProjectReference Include="..\Adham.Common\Adham.Common.csproj" />
    <ProjectReference Include="..\Adham.Core\Adham.Core.csproj" />
    <ProjectReference Include="..\Adham.Tools.Files\Adham.Tools.Files.csproj" />
    <ProjectReference Include="..\Adham.Tools.Search\Adham.Tools.Search.csproj" />
  </ItemGroup>
</Project>
